# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: github-actions
  schedule:
    - cron: 0 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: shimataro/ssh-key-action@v2.0.1
      with:
        key: {{ secrets.GITHUB_SSH }}
        known_hosts: github.com
      run: git clone --mirror https://github.com/pmusolino/Wormholy.git Wormholy
      run: cd Wormholy
      run: git remote add --mirror=fetch mine git@github.com:alenpeter/Wormholy.git
      run: git fetch origin
      run: git push mine --all
      run: echo completed
        
